# Generated by Django 4.2.7 on 2024-06-15 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('call_app', '0003_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('enroll_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_enrolled', models.DateTimeField(auto_now_add=True)),
                ('payment_status', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='call_app.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='call_app.student')),
            ],
        ),
        migrations.DeleteModel(
            name='CourseContent',
        ),
    ]
