# Generated by Django 4.2.7 on 2024-06-15 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('call_app', '0004_enrollment_delete_coursecontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacher_id', models.AutoField(primary_key=True, serialize=False)),
                ('registered_date', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='VideoChat',
            fields=[
                ('chat_id', models.AutoField(primary_key=True, serialize=False)),
                ('scheduled_date', models.DateTimeField()),
                ('duration', models.IntegerField(help_text='Duration in minutes')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='call_app.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='call_app.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='call_app.teacher')),
            ],
        ),
    ]
